### ISSUE TITLE
SnagIt PKG recipe failing

### ISSUE THREAD

**Issue by SmithersJr** [autopkg/bkerns-recipes#1]
```
Error in com.github.autopkg.kernsb.pkg.TechSmithSnagit: Processor: TechSmithAddScriptKey: Error: [Errno 2] No such file or directory: '/Users/cmcadmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.bkerns-recipes/TechSmithSnagit/Scripts/postinstall'
```

It looks like maybe there is a remnant of the "postinstall" script you removed.

**Comment by kernsb** [comment]
Thanks for the heads up. That wasn't actually intended to be removed, just ignored so that my reg key wasn't being shown to the world. Should be fixed now. It is only used for adding your reg key to the package with an override.

**Comment by kernsb** [comment]
One side note, there is an oddity with the pkg since 4.x that I haven't figured out yet. It seem that when 3.x is already present on the machine, it wants to install into a ".localized" folder instead of overwriting the existing app. Working on that one.

**Comment by SmithersJr** [comment]
Gotcha. Feel free to delete my PR then. ;-)

**Comment by SmithersJr** [comment]
> It seem that when 3.x is already present on the machine, it wants to install into a ".localized" folder instead of overwriting the existing app. 

Are you referring to the app showing up in `\Applications\Snagit\Snagit.app` instead of `\Applications\Snagit.app`

**Comment by kernsb** [comment]
Yep, that Snagit folder is actually "Snagit.localized" (extension hidden in Finder)

I find that if I completely gut 3.x from the system first, then it installs normally. Very strange.
