### ISSUE TITLE
TechSmithCamtasia.pkg/jss Camtasia Registration Key Unified License file

### ISSUE THREAD

**Issue by dvdbyd** [autopkg/bkerns-recipes#10]
/Users/Shared/TechSmith/Camtasia/Camtasia\ Registration\ Key\ Unified\ License file is not created with Camtasia 3-3.1.2.pkg and is therefore not written to with regkey with current postinstall script when packaged. /Users/Shared/TechSmith/Camtasia/Camtasia\ Registration\ Key RegKey is not created following install, as currently expected by postinstall.

./postinstall: /Users/Shared/TechSmith/Camtasia/Camtasia Registration Key.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Camtasia Registration Key.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/Shared/TechSmith/Camtasia/Camtasia Registration Key.plist, NSUnderlyingError=0x7fa3cf707400 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})

Thanks in advance!

**Comment by kernsb** [comment]
I have updated the postinstall script for the 2018 changes and new license filename.

I have tested the process with embedding the key in the pkg start-to-finish, with it working successfully. Let me know if you continue to have issues.
