### ISSUE TITLE
Techsmith Camtasia has changed

### ISSUE THREAD

**Issue by haircut** [autopkg/bkerns-recipes#11]
The filename of the app in the disk image is now "Camtasia 2018.app" so the recipe fails when attempting to copy the app.

https://github.com/autopkg/bkerns-recipes/blob/master/TechSmithCamtasia/TechSmithCamtasia.pkg.recipe#L54-L64 highlights the problem processor where the paths should be changed to reflect the new app name.

**Comment by kernsb** [comment]
I’ll adjust. Had to do the same for Snagit a bit back. Thanks for the heads-up!

Brandon

**Comment by haircut** [comment]
😁 that may be the fastest issue response in the history of autopkg

**Comment by kernsb** [comment]
This has been adjusted.

**Comment by beatlemike** [comment]
@kernsb seems like TechSmith did it again, something changed and Camtasia 2019 doesn't seem to work with the script generated Camtasia Registration Key Unified License
