### ISSUE TITLE
TechSmith Camtasia preinstall.sh no longer accurate

### ISSUE THREAD

**Issue by beatlemike** [autopkg/bkerns-recipes#14]
With Camtasia 2018.app being replaced by Camtasia 2019.app, the preinstall script introduces a breaking space after the word "Camtasia" in the app name. The script then fails.

**Comment by kernsb** [comment]
I believe this should be resolved with the edit I made to the script. Please confirm!

**Comment by beatlemike** [comment]
Looks good so far. At least I don’t see any failure. Thanks!!
