### ISSUE TITLE
Snagit preinstall script error

### ISSUE THREAD

**Issue by WaveBirdDash** [autopkg/bkerns-recipes#19]
Running a package created with the Snagit recipes returns an error during the preinstall script run:

```
installd[1047]: ./preinstall: /tmp/PKInstallSandbox.QIKAGC/Scripts/com.TechSmith.Snagit2020.KvJZRI/preinstall: line 9: syntax error near unexpected token `<'
installd[1047]: ./preinstall: /tmp/PKInstallSandbox.QIKAGC/Scripts/com.TechSmith.Snagit2020.KvJZRI/preinstall: line 9: `done < <(echo "${oldVersions}")'
```

**Comment by jlehikoinen** [comment]
How about using `find` and `rm` combo in the preinstall script?

`/usr/bin/find /Applications -maxdepth 1 -type d -iname "snagit*" -print0 -exec rm -r {} \; > /dev/null`

**Comment by beatlemike** [comment]
I'm getting the same errors during the installation

Been replacing the preinstall script with

```
oldVersions=$(ls -1 /Applications | grep "Snagit")

for oldVersion in $oldVersions; do
   /bin/rm -rf "/Applications/${oldVersion}"
done
```
