### ISSUE TITLE
Unable to push Camtasia via autopkg

### ISSUE THREAD

**Issue by tsinghzf** [autopkg/bkerns-recipes#24]
TechSmithCamtasia.jss.recipe
        Error in com.github.autopkg.kernsb.jss.TechSmithCamtasia: Processor: CodeSignatureVerifier: Error: Error processing path '/private/tmp/dmg.Rnyoem/Camtasia 2019.app

**Comment by WaveBirdDash** [comment]
This is a duplicate of #23.

**Comment by kernsb** [comment]
Fixed by 74f08b9 merge
