### ISSUE TITLE
Camtasia License

### ISSUE THREAD

**Issue by beatlemike** [autopkg/bkerns-recipes#25]
Command line to get the Camtasia key is no longer functional with 2020. It uses a completely different license file

**Comment by beatlemike** [comment]
I spoke with our rep who got me in touch with some one at TechSmith support and there may a useable solution soon, but for 2020.0.1 it's not yet possible

**Comment by WaveBirdDash** [comment]
Sounds like 2020.0.2 will support this functionality (with a new file path and workflow). It's available as a Google Drive link until their site gets updated, with setup instructions here:

https://support.techsmith.com/hc/en-us/articles/203727638-Camtasia-Mac-Enterprise-Install-Guidelines

That said, the postinstall script will need to be changed to reflect the new workflow. I'll take a look at the script and see what needs to be adjusted.

**Comment by WaveBirdDash** [comment]
Now that 2020.0.2 is live in the app feed (rather than just a Google Drive download), I've proposed an update to the postinstall script that plays nice by the new workflow. #27

**Comment by beatlemike** [comment]
Great!

**Comment by kernsb** [comment]
Resolved by #27 merge
