### ISSUE TITLE
Wrong download Snagit

### ISSUE THREAD

**Issue by ahousseini** [autopkg/bkerns-recipes#33]
The recipe `com.github.autopkg.kernsb.download.TechSmithSnagit` downloads an old version of Snagit since today. When I run the recipe I get this url:
`'url': 'http://download.techsmith.com/snagitmac/releases/19111/snagit.dmg',`

**Comment by rtrouton** [comment]
I'm seeing the same issue, where Snagit 2019.1.11 is being downloaded. 

It looks like this address pulls the latest Snagit installer .dmg: https://download.techsmith.com/snagitmac/releases/Snagit.dmg

**Comment by kernsb** [comment]
Fixed by #34
