### ISSUE TITLE
TechSmithSnagIt.download error

### ISSUE THREAD

**Issue by grahampugh** [autopkg/bkerns-recipes#4]
```
The following recipes failed:
    TechSmithSnagIt.download
        Error in com.github.autopkg.kernsb.download.TechSmithSnagit: Processor: TechSmithURLProvider: Error: No JSON object could be decoded
```

**Comment by kernsb** [comment]
I'll take a look at it. Thanks for letting me know!



On Feb 28, 2017, at 10:52 AM, Graham R Pugh <notifications@github.com<mailto:notifications@github.com>> wrote:


The following recipes failed:
    TechSmithSnagIt.download
        Error in com.github.autopkg.kernsb.download.TechSmithSnagit: Processor: TechSmithURLProvider: Error: No JSON object could be decoded


-

**Comment by grahampugh** [comment]
Hi,
I took a look too. the problem is with the TechSmithURLProvider, which the TechSmithSnagit.download.recipe doesn't seem to actually use. Once I removed the reference to this in the download recipe, it ran through fine. I can provide a pull request if required.

**Comment by kernsb** [comment]
That is actually a mistake. The download recipe for SnagIt should use the URL Provider, just as the Camtasia recipe does. I have now adjusted this and successfully tested using the .pkg recipe. Which variant are you using? (pkg/munki/jss)

Brandon

**Comment by kernsb** [comment]
This was corrected.
