### ISSUE TITLE
TechSmith.pkg.recipe - adding reg key

### ISSUE THREAD

**Issue by grahampugh** [autopkg/bkerns-recipes#5]
Hi again,
Are you able to explain how this is supposed to work?
I added our key to the `SNAGIT_KEY` key in our recipe override, and the correct file path is created (`/Users/Shared/TechSmith/Snagit`), but no file is written.
In our existing manual setup, the file `SnagitRegistrationKey` is created, which is a plist with the following content (note a `data` value instead of a `string` value):

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>RegKey</key>
	<data>
	//XXXYYYYXXXXYYYXXXXYYYXXXXXXYYYYYXXXXXYYYXXXXYYYYYYXXXXXXXYYYYXXX
	XXXYYYXXXXXXY
	</data>
</dict>
</plist>
```

Does this reflect your setup? If so, in what form should I enter the key into the recipe?

**Comment by kernsb** [comment]
It should be in the same form as what you find in the plist file that you reference. All it really does is add a postinstall script to create that file and entry.

Brandon

**Comment by kernsb** [comment]
To clarify, run the following commands on a machine where the reg key has been manually added to get the value that should be used in your override file:

```
cp /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey.plist

defaults read /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey.plist RegKey | sed 's/[<> ]//g'
```

Let me know if this resolves the issue!

**Comment by kernsb** [comment]
No further response. Assuming the was resolved with the info provided.

**Comment by thereal-kcsantos** [comment]
Please forgive me, but I'm new to AutoPKG and this is one of the first packages recipes I've been digging into!

#### I'm stuck on this.

> To clarify, run the following commands on a machine where the reg key has been manually added to get the value that should be used in your override file:
> 
> ```
> cp /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey.plist
> 
> defaults read /Users/Shared/TechSmith/Snagit/SnagitRegistrationKey.plist RegKey | sed 's/[<> ]//g'
> ```
> 
> Let me know if this resolves the issue!


Here's the file plist file from that commands in terminal:
<img width="833" alt="Screen Shot 2020-08-03 at 4 43 07 PM" src="https://user-images.githubusercontent.com/46388876/89255832-8d16fb80-d5d7-11ea-82d2-b17bf31ee634.png">

Notice on Lines 14 & 15 where I added the SNAGIT_KEY: 
<img width="913" alt="Screen Shot 2020-08-03 at 5 06 05 PM" src="https://user-images.githubusercontent.com/46388876/89255919-cbacb600-d5d7-11ea-9086-adb9f9f9eee0.png">

I'm not sure if I did this correctly. The Package I end up with does not install the SnagIt Registration key in /Users/Shared/TechSmith/ directory (matter of fact, i'm missing the "SnagIt" folder in that directory unless I manually enter the Registration key.)


Thank you in advance!
