### ISSUE TITLE
TechSmith change in app name within DMG causing error in processing Snagit application

### ISSUE THREAD

**Issue by multiday** [autopkg/bkerns-recipes#6]
Error returned in processing - Error in local.jss.TechSmithSnagit: Processor: Copier: Error: Error processing path '/private/tmp/dmg.../Snagit.app' with glob.

 Getting error in the Copier processor because TechSmith has changed the name of the app in the DMG from "Snagit.app" to "Snagit 2018.app". Unless there is a general way to get the filename, line 60 in TechSmithSnagit.pkg.recipe would need to be changed to the new file name. Changing the destination name line 62 could be done or not.

```
54        <dict>
55           <key>Processor</key>
56            <string>Copier</string>
57            <key>Arguments</key>
58            <dict>
59                <key>source_path</key>
60                <string>%pathname%/Snagit.app</string>
61                <key>destination_path</key>
62                <string>%pkgroot%/Applications/Snagit.app</string>
63            </dict>
64       </dict>
```

**Comment by MLBZ521** [comment]
Seeing the same issue as well.

Updated so recipe is not version specific
+ Updated to use %app_name% for the source_path and destination_path keys in the Copier Processor.
+ Updated to use %bundleid% in the PkgCreator Processor.

See pull request:  #7

**Comment by MLBZ521** [comment]
Just realized the preinstall script will be affected as well.

Updated preinstall script for Snagit .app name change.  See pull request #8

**Comment by kernsb** [comment]
Changes by Zack T have been merged to correct this issue. Thanks for the contribution, Zack!
